### ISSUE TITLE
Fast access to POS (Cash Register)

### ISSUE THREAD

**Issue by designsats** [GaloyMoney/blink-mobile#2802]
POS is too deep in settings. Many new users have no idea it exists. (I see it daily) 

Proposal: Change "Way to get paid" item in Settings to "Cash register" and open it in browser on click. 
Change the icon to "Calculator" icon. 

![dark theme - menu](https://github.com/GaloyMoney/galoy-mobile/assets/17384787/17ee2af8-f60b-42fb-8851-54e4391732eb)

**Comment by nicolasburtey** [comment]
you would remove the associated "ways to get paid" screen?

**Comment by sandipndev** [comment]
> you would remove the associated "ways to get paid" screen?

Same question @designsats

**Comment by designsats** [comment]
@sandipndev @nicolasburtey Yes. Screen would be gone. Paycode is on Recieve screen and Printable code is inside POS (not used often anyways).

**Comment by sandipndev** [comment]
I like the name Point of Sale as opposed to Cash Register. It's more direct. I thought @agbegin was of the same opinion too.

Let's rename it to Point of Sale. Self assigning this and working on it within an hour if no more discussion is required.

**Comment by nicolasburtey** [comment]
shouldn't need a screen documenting how the Point of sales work instead of just opening a link when tapping on the button?

I feel that people don't understand that this is a link that can be shared to other people for instance. I don't think opening the link in a browser would really help convey this information

**Comment by designsats** [comment]
done, closing
